### ISSUE TITLE
New add-ons aim to require at least PHP 5.6

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-attendee-importer#1]
This is a reminder that before we release a new add-on we're setting a minimum requirement for PHP version 5.6 or greater. We did this for the Wait List add-on and it's helping incentivize updating from older PHP.

**Comment by mnelson4** [comment]
ok good point; ya may as well bump that up...

thinking about it, I could have gotten that reviewed and tested following the normal process... d'oh.

@tn3rb do you mind doing an informal review of the above?

**Comment by mnelson4** [comment]
bah I also need to finish setting this repo up properly.(eg syncing tags) that will help especially how we're technically starting with a working add-on (although it does nothing)

**Comment by mnelson4** [comment]
Bah, nevermind. Everthing that's in master will need a top-to-bottom review anyway.  So we'll review then. For now, I'm pretty sure this is done (somebody reopen if they don't think so)
