### ISSUE TITLE
Avoid duplicate contacts

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-attendee-importer#11]
I'm not sure if this is part of the plan or not, but in case it's not: 

If a previously registered contact is already in the db, will there be a check so the new registration gets attached to the existing contact?

**Comment by mnelson4** [comment]
Yes I'm hoping to avoid duplicates contacts. 
I'm kinda thinking the check for duplicate contacts will be based on firstname, lastname, email, just like in SPCO. Let me know if that's insufficient.

**Comment by joshfeck** [comment]
Works for me.

**Comment by mnelson4** [comment]
hmmm, for the record, so far on #13 we are getting duplicate attendees... :thinking:

**Comment by mnelson4** [comment]
Actually now, on master, we're not getting duplicate contacts. This will need to be double-checked again before release.
