### ISSUE TITLE
Incorporate capabilities

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-attendee-importer#14]
## Issue Overview

Not everyone should be able to use the attendee importer. We need to decide what capabilities depend on it, and where to require those capabilities.

**What cap?** This is primarily creating registrations, transactions, payments, and answers. We could require each of those capabilities individually, but it would be weird an import only imported SOME of the data, eg attendees with no transactions or payments. I'm open to suggestion what capability will be best.

**When to apply?** Probably when deciding to show the admin page, and during the commands that actually import data (in case those maybe someday get invoked from some other interface? It's a bit of a stretch but if it's easy it would be good.)

## Bug report or feature request?

* [x] Bug until it gets implemented it will be a bug.
* [ ] Feature
* [ ] Neither

## Steps to Reproduce (for bugs)

Go to import event data.

## Expected Behaviour

Only admin-ey users should be able to import from a CSV.

## Current Behaviour

Currently anyone can.

**Comment by mnelson4** [comment]
FYI currently the user needs to have the `import` capability, but the admin pages don't appear unless you are an `administrator`. 
@joshfeck what caps do you think the user should need to use the importer? It might not be bad to add a custom capability like `ee_importer` or `ee_import_attendees`. Thoughts?

**Comment by joshfeck** [comment]
I'm unsure we'd want to add new capabilities for this. Unless that's something that will help with managing access for Event Smart subscribers.

I would think `import` + the `ee_edit_registrations` cap might be a good fit here. 

So unless there's something additional needed for ES, I'd say we go with `import` + `ee_edit_registrations`.

**Comment by garthkoyle** [comment]
When it comes to importing attendees into events on Event Smart, I think a staff member will be the one doing the import. At least until we can have separate sub-accounts in Mandrill for each site that we can monitor, set limits on and shut down if the event organizer starts sending spam. Otherwise, we run a real risk of people importing the attendees, then using the Batch email tool to send email spam.

Doing the import ourselves we can try to be more certain that the data is imported correctly and charge a price based on the number of records.

But if we did make the import accessible, we would probably need a specific capability to access the page that's different than the capabilities we have now so we can control who has access to those features.

**Comment by mnelson4** [comment]
> I would think import + the ee_edit_registrations cap might be a good fit here.

Thanks @joshfeck.  This is the first time we've wanted an admin page to only appear if a user has TWO caps, and would require some refactoring of the corresponding admin code. So this would be a little tricky.

Thinking about it though: remember the admin menu item should point to *all* EE importers (theoretically there will be a few), and it only sends them directly to the attendee importer if there are no others available. 
So IMO it might be good to only show the admin menu item (which should really be named just "Import", so it's more generic) if they have "import" cap. Then, only allow them to use the attendee importer if they have "ee_edit_registrations". That would be really easy code-wise and I think achieves the same thing. (In the odd case that the user can import, but not edit registrations, we would just show some type of notice. :cry: but IMO there are bigger priorities)

>  I think a staff member will be the one doing the import. 

@garthkoyle I think that's a great way to do it initially. For the reasons you mentioned, plus we'd be actual users of our own product and so would probably see other ways to improve it.

Then, if we want to allow users to import themselves, we'd probably need to add a new cap later.

**Comment by mnelson4** [comment]
The associated PR was merged in. We're adding new caps (it's actually much easier than trying to require TWO caps to do something)
