### ISSUE TITLE
Summarize Import

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-attendee-importer#19]
## Issue Overview

After an import is done, I suspect folks will want to know what exactly what imported. What information should we include in the MVP?
I suspect just knowing the counts would be good: 291 contacts, 389 registrations, 1230 answers to custom questions, 100 payments, 150 transactions. (Maybe leave out line items because users won't know how to interpret that anyway; maybe answers should be left out too.)
If we're just going to show them the counts, it will be really easy to store that on the import config.
But if we want to list them out (and provide a link to them), how exactly we're going to store that data will merit some discussion. If we put it all into one option, it might get too big and then have errors; so we would maybe want to store the extra metas on all the imported stuff; or maybe even create a totally new database table dedicated to tracking imported data.

Note: this might be less important if we implement the "import preview" that Darren had advocated for; and it will be more important if we implement "reverting" an import.

@joshfeck do you have thoughts on the UI/UX of this? (Once we have an idea of what we'd like it to look like, let's discuss the technical details).

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

**Comment by joshfeck** [comment]
I don't think we need counts. A success message is sufficient, and we could add a link to view the registrations for the event that was imported to. See also step 5 here:
https://github.com/eventespresso/eea-attendee-importer/issues/16


Since we should already have the event ID, how about we display a "View registrations" link similar to the link that's included in the Event List table that navigates to the list of registrations for that event?

**Comment by mnelson4** [comment]
> Since we should already have the event ID, how about we display a "View registrations" link similar to the link that's included in the Event List table that navigates to the list of registrations for that event?

Oh sure, like instead of the existing "Next" button? Ya that sounds good. (When/if we support importing to multiple events simultaneously, we'll need to rethink that, but for now this is totally fine.)

**Comment by mnelson4** [comment]
Oups, mostly just meant to touch this ticket with that commit. 
[This is what it looks like](https://drive.google.com/a/eventespresso.com/file/d/1bWjF_TwnjhMZb0vjWPjmrkFjLVkV5GS-/view?usp=drivesdk), and it sends the user to the event registrations list table that they were just imported to. (If, someday, we support importing to multiple events simultaneoulsy, this can be adjusted to dynamically decide to send them to the generic registrations list table instead.)

**Comment by mnelson4** [comment]
hmmmm... also I made the last request directly to master, thinking I'd do all the development there, but that makes code reviews stink again. I won't do that for subsequent commits.

**Comment by mnelson4** [comment]
@joshfeck does this look good to you? (Just with regards to the "completion" step sending the user to the event registrations list table.)

**Comment by mnelson4** [comment]
I'm just going to close this for now. It will come up again when doing final testing before MVP.
