### ISSUE TITLE
Reorganize steps

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-attendee-importer#20]
## Issue Overview

On issue https://github.com/eventespresso/eea-attendee-importer/issues/18#issuecomment-479550984, Brent suggested
> One other issue I thought of that might change how the form steps are laid out, is that we should maybe have the admin choose the event and ticket first, because that will change what questions are available for the system.

> As it is now, you connect the CSV columns with questions before choosing the event. This means we are loading EVERY QUESTION in the db, whereas they likely only need to see the questions for that specific event. Having them choose the event first means that we could only query for those questions, which will make the process of connecting them to CSV columns much easier.

We chatted a little in slack about it. Currently, we had decided to choose event and ticket after mapping the columns because they can be skipped if, when we support having an event or ticket column, the CSV mapping indicates which tickets to register users for.

But then we thought we could put the event and ticket steps first, and either
A) make them optional (so if the user didn't select an event or ticket, they would be required to map the so-far-unmade event or ticket column)
B) make them a default, which would be overridden by using the event or ticket column

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

**Comment by joshfeck** [comment]
Probably should put the event selection first. Once they've selected an event, the ticket selection could appear later if there's more than one ticket. The ticket selection could be an optional step if there's a ticket column to map to.

**Comment by mnelson4** [comment]
PR merged
