### ISSUE TITLE
Fill in usage tab

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-attendee-importer#21]
## Issue Overview

We need to put some content in the usage tab or remove it. Requested on https://github.com/eventespresso/eea-attendee-importer/issues/16.

I think it's best to do this once we are otherwise ready for release. Also, I'm ok with just documenting it on ee.com

## Bug report or feature request?

* [ ] Bug
* [ ] Feature
* [x] Neither

**Comment by joshfeck** [comment]
Actually can you remove the tabs? We can do a pull down help tab instead. Like the help tab that's included on the Event Espresso > Registrations page.

<img width="1102" alt="Screen Shot 2019-04-12 at 6 39 12 PM" src="https://user-images.githubusercontent.com/891156/56157351-4db13f80-5f8d-11e9-9475-976709eb4106.png">


This will help avoid navigating away from the import steps unintentionally and avoid the fatal error that occurs when clicking on the tab labeled "Import".

**Comment by mnelson4** [comment]
Sure, good idea

**Comment by mnelson4** [comment]
I should also tidy up the admin here.

**Comment by mnelson4** [comment]
PR merged
