### ISSUE TITLE
Avoid importing empty rows

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-attendee-importer#31]
## Issue Overview

I had a few empty rows in the spreadsheet 
<img width="1008" alt="Screen Shot 2019-04-17 at 12 13 11 PM" src="https://user-images.githubusercontent.com/891156/56304230-ab6b9600-610b-11e9-8b4b-ae99e9eb1287.png">

and the export to CSV just made some empty rows. 
<img width="830" alt="Screen Shot 2019-04-17 at 12 13 51 PM" src="https://user-images.githubusercontent.com/891156/56304238-aeff1d00-610b-11e9-9640-0766eb2f94d5.png">

Which ended up getting imported as blank registrations.
![Screen Shot 2019-04-17 at 12 22 37 PM](https://user-images.githubusercontent.com/891156/56304245-b1fa0d80-610b-11e9-9c8f-c4caef1ad72e.png)

## Expected Behaviour

If no data then skip the import for that row.

**Comment by mnelson4** [comment]
oh I hadn't thought about this case. Ya I can have a check for blank rows.

**Comment by mnelson4** [comment]
PR merged
