### ISSUE TITLE
Swap out all instances of the string "Event Espresso" in all i18n-ready strings

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-attendee-importer#34]
After https://github.com/eventespresso/event-espresso-core/issues/1183 is merged to core, we'll need to remove the string "Event Espresso" and replace with a placeholder. This will help make it easier to rebrand the Attendee Importer add-on for Event Smart.

- [ ] Will also need to bump the minimum EE core version requirement in this add-on

**Comment by mnelson4** [comment]
Taken care of on https://github.com/eventespresso/eea-attendee-importer/pull/35
